### ISSUE TITLE
Suggestion: make API base URL configurable

### ISSUE THREAD

**Issue by andypiper** [stefanuros/deno_twitter_api#1]
At the moment, this client assumes that the API is always accessed via api.twitter.com/1.1

With the Twitter Ads API, this is ads-api.twitter.com/$currentversion

With the Twitter Developer Labs endpoints (new version of the Twitter API) this is currently api.twitter.com/labs/$currentversion

One suggestion would be to make the API base settable in some way (assuming this is possible given security restrictions / design of deno)

**Comment by stefanuros** [comment]
That's a good idea. Initially, this was made for a project I'm working on and so it focuses mostly on the features I needed so I will need to look into the details of what else I will need to add but that is definitely part of my plan for the future. For now, I'll add a getter and setter for the base URL, to allow these cases.

**Comment by stefanuros** [comment]
I have made the change. I will look into adding more features in the future. https://github.com/stefanuros/deno_twitter_api/commit/8b3d2421dddfb1a4a9c02d3d0dd588cd36a92d93
