### ISSUE TITLE
Guidance: Making POST requests returns "could not authenticate"

### ISSUE THREAD

**Issue by 0xVesion** [stefanuros/deno_twitter_api#2]
Running the provided example for me the first two requests succeed, but the post requests fail with the following error message:
Status: 401
```json
{"errors":[{"code":32,"message":"Could not authenticate you."}]}
```
Can someone give me some pointers as to why this is happening?

**Comment by stefanuros** [comment]
Hi, the POST examples were not functional and were put there to show how post functions might be used. I will make this more clear in the example. If you want to use a post request to make a tweet for example, you will need to follow these steps.  This will give you the ability to authenticate a user so you can use post requests. https://developer.twitter.com/en/docs/basics/authentication/oauth-1-0a/obtaining-user-access-tokens.
