### ISSUE TITLE
Crashed when running this api on Heroku

### ISSUE THREAD

**Issue by killvung** [stefanuros/deno_twitter_api#3]
I wrote a simple application that would call `statuses/user_timeline.json` from the API's `get()`. This work on my local machine, but when I ran it on Heroku it returns `Internal Server Error`.  This is my Profile for Heroku.
`web: deno run --allow-read --allow-net --cached-only index.ts --port=${PORT}`
The same thing if I set `--allow-net` with specific port, for example `--allow-net=${PORT}`

I am still investigation if it's related to the build pack or the API.
https://github.com/chibat/heroku-buildpack-deno/blob/master/bin/compile 
The API for `get()` looks straightforward.
https://github.com/stefanuros/deno_twitter_api/blob/master/twitterApi.ts#L59

**Comment by stefanuros** [comment]
Are you able to post the error that occurred or is that hidden? What values were being passed into the TwitterApi object? Can you confirm if the crash happens if you don't run the twitter API?

**Comment by killvung** [comment]
UPDATE: I suspected the issue is coming from Heroku itself. When I deployed the app with this api on fly.io it works. I am going to close the issue now. But yeah thanks for the library to save a bunch of work.
